# Generated by Django 5.1 on 2024-09-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200)),
                ('cena', models.CharField(max_length=200)),
                ('sklad', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
